module.exports = {   //模块.导出
    configureWebpack:{  //配置Web包
        //扩展webpack
        devServer :{  //开发服务器
            before(app){
                app.get('/api/goods',function(req,res){
                    res.json({
                        code:0,
                        data:[
                            {
                                id:1,
                                text:'vue.js',
                                price:'100',
                                img:'1.jpg',
                                count:100
                            },
                            {
                                id:2,
                                text:'node.js',
                                price:'200',
                                img:'2.jpg',
                                count:200
                            },
                            {
                                id:3,
                                text:'角度看.js',
                                price:'80',
                                img:'3.jpg',
                                count:100
                            },
                            {
                                id:4,
                                text:'非官方.js',
                                price:'80',
                                img:'1.jpg',
                                count:100
                            },
                            {
                                id:5,
                                text:'耳语.js',
                                price:'80',
                                img:'1.jpg',
                                count:100
                            },
                            {
                                id:5,
                                text:'孤独感.js',
                                price:'80',
                                img:'1.jpg',
                                count:100
                            },
                            {
                                id:5,
                                text:'东方时尚.js',
                                price:'80',
                                img:'1.jpg',
                                count:100
                            },
                            {
                                id:5,
                                text:'通用图.js',
                                price:'80',
                                img:'1.jpg',
                                count:100
                            },
                            {
                                id:5,
                                text:'耳语.js',
                                price:'80',
                                img:'1.jpg',
                                count:100
                            },
                            {
                                id:5,
                                text:'蒂夫.js',
                                price:'80',
                                img:'1.jpg',
                                count:100
                            },

                        ]
                    });
                });
            }
        }
    }
}